apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: bankapp-namespace
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: VGVzdEAxMjM=  # Base64 for "Test@123"
  SPRING_DATASOURCE_PASSWORD: VGVzdEAxMjM= # Base64 for "Test@123"

